import { jsPDF } from "jspdf";
import { toPng } from "html-to-image";
import pptxgen from "pptxgenjs";
import { v4 as uuidv4 } from "uuid";

// Extract content from markdown for PPT
function extractPptContent(markdown: string) {
  const getSection = (title: string, length = 500) => {
    const idx = markdown.indexOf(title);
    if (idx === -1) return "No content found";
    const startIdx = markdown.indexOf("\n", idx) + 1;
    const endIdx = markdown.indexOf("## ", startIdx);
    const content = endIdx !== -1 ? markdown.substring(startIdx, endIdx) : markdown.substring(startIdx);
    return content.trim().substring(0, length);
  };

  const overview = getSection("## 3. 数据质量评估").substring(0, 300) || getSection("## 1. 数据资产识别").substring(0, 300) || "Data Overview Placeholder";
  const insights = getSection("## 8. 关键业务洞察") || getSection("洞察");
  const strategy = getSection("## 9. 一句话业务策略", 150) || getSection("策略");

  return { overview, insights, strategy };
}

export async function exportToPDF(elementId: string, datasetName: string) {
  const element = document.getElementById(elementId);
  if (!element) return;
  
  // We will generate a PDF with a standard A4 cover page, 
  // and a single long continuous page for the content so charts and text don't get cut in half.
  
  // 1. Create a beautiful cover div
  const coverWidth = 800;
  const coverHeight = 1130;
  
  const coverDiv = document.createElement("div");
  coverDiv.style.position = "absolute";
  coverDiv.style.top = "-9999px";
  coverDiv.style.left = "-9999px";
  coverDiv.style.width = `${coverWidth}px`;
  coverDiv.style.height = `${coverHeight}px`;
  coverDiv.style.backgroundColor = "#0F0F0F"; // Dark theme cover!
  coverDiv.style.color = "#F5F4F0";
  coverDiv.style.display = "flex";
  coverDiv.style.flexDirection = "column";
  coverDiv.style.justifyContent = "center";
  coverDiv.style.padding = "100px";
  coverDiv.style.boxSizing = "border-box";
  coverDiv.style.fontFamily = "'PingFang SC', 'Microsoft YaHei', 'Helvetica Neue', Arial, sans-serif";
  
  coverDiv.innerHTML = `
    <div style="flex: 1; display: flex; flex-direction: column; justify-content: center;">
      <h3 style="font-size: 24px; color: #FF3B00; font-style: italic; letter-spacing: 2px; text-transform: uppercase; margin-bottom: 30px;">Enterprise Intelligence</h3>
      <h1 style="font-size: 64px; font-weight: 800; line-height: 1.1; margin-bottom: 40px; letter-spacing: -2px;">数据分析洞察报告</h1>
      
      <div style="width: 60px; height: 8px; background-color: #FF3B00; margin-bottom: 60px;"></div>
      
      <div style="font-size: 20px; color: #A3A3A3; display: flex; flex-direction: column; gap: 16px;">
        <div style="display: flex; align-items: center; justify-content: space-between; border-bottom: 1px solid #333; padding-bottom: 16px;">
          <span style="letter-spacing: 1px;">DATASET</span>
          <span style="color: #F5F4F0; font-weight: 500;">${datasetName}</span>
        </div>
        <div style="display: flex; align-items: center; justify-content: space-between; border-bottom: 1px solid #333; padding-bottom: 16px;">
          <span style="letter-spacing: 1px;">GENERATED DATE</span>
          <span style="color: #F5F4F0; font-weight: 500;">${new Date().toLocaleDateString()}</span>
        </div>
        <div style="display: flex; align-items: center; justify-content: space-between; border-bottom: 1px solid #333; padding-bottom: 16px;">
          <span style="letter-spacing: 1px;">ENGINE</span>
          <span style="color: #FF3B00; font-weight: 700; font-style: italic;">Smart Report Engine™</span>
        </div>
      </div>
    </div>
    
    <div style="font-size: 14px; color: #666; text-align: center; border-top: 1px solid #333; padding-top: 24px;">
      CONFIDENTIAL & PROPRIETARY · GENERATED BY AI
    </div>
  `;
  document.body.appendChild(coverDiv);
  
  // High quality render
  const coverImgData = await toPng(coverDiv, { pixelRatio: 2 });
  document.body.removeChild(coverDiv);
  
  // 2. Initialize PDF with A4 dimensions for cover
  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "px",
    format: [coverWidth, coverHeight]
  });
  
  pdf.addImage(coverImgData, "PNG", 0, 0, coverWidth, coverHeight);
  
  // 3. Render the actual report content
  // We use filter to exclude certain problematic elements if needed, but here it's fine.
  const contentImgData = await toPng(element, { 
    pixelRatio: 2,
    backgroundColor: '#ffffff'
  });
  
  const imgProps = pdf.getImageProperties(contentImgData);
  
  // Calculate width/height. We will make the PDF page match the image perfectly to prevent cutting.
  // Add a nice 40px margin around the content
  const margin = 40;
  const targetWidth = coverWidth; // Keep same width as cover
  const renderWidth = targetWidth - margin * 2;
  const renderHeight = (imgProps.height * renderWidth) / imgProps.width;
  const targetHeight = renderHeight + margin * 2;
  
  // Add a new page with custom height so everything fits continuously!
  pdf.addPage([targetWidth, targetHeight], "portrait");
  
  pdf.addImage(contentImgData, "PNG", margin, margin, renderWidth, renderHeight);
  
  // 4. Save
  const fileName = `${datasetName.replace(/\.[^/.]+$/, "")}_分析报告_Long.pdf`;
  pdf.save(fileName);
}

export async function exportToPPT(datasetName: string, markdown: string) {
  const pres = new pptxgen();
  
  pres.layout = "LAYOUT_16x9";
  
  // Theme styling
  const themeColor = "FF3B00";
  const darkColor = "0F0F0F";
  const lightColor = "F5F4F0";
  const grayColor = "A3A3A3";
  const fontFace = "PingFang SC, Microsoft YaHei, sans-serif";

  // Slide 1: Cover
  let slide1 = pres.addSlide();
  slide1.background = { color: darkColor };
  
  slide1.addText("Enterprise Intelligence", {
    x: 1.0, y: 1.5,
    w: "80%",
    color: themeColor,
    fontSize: 18,
    bold: true,
    fontFace
  });

  slide1.addText("数据分析洞察报告", { 
    x: 1.0, y: 2.2, 
    w: "80%", 
    color: lightColor, 
    fontSize: 48, 
    bold: true,
    fontFace
  });
  
  slide1.addShape(pres.ShapeType.rect, { x: 1.0, y: 3.2, w: 1.0, h: 0.1, fill: { color: themeColor } });

  slide1.addText(`DATASET: ${datasetName}\nDATE: ${new Date().toLocaleDateString()}\nENGINE: Smart Report Engine™`, { 
    x: 1.0, y: 3.8, 
    w: "80%", 
    color: grayColor, 
    fontSize: 14,
    lineSpacing: 32,
    fontFace
  });

  // Extract content dynamically
  const lines = markdown.split('\n');
  let currentTitle = "";
  let currentContent = "";
  
  const addContentSlide = (title: string, text: string) => {
    if (!text.trim() || !title.trim()) return;
    
    // Split long text into multiple slides if needed
    // pptxgenjs doesn't auto-paginate cleanly for very long text, so we split by paragraphs
    const paragraphs = text.split(/\n\n+/).filter(p => p.trim() !== '');
    
    let currentSlideText = "";
    
    for (let i = 0; i < paragraphs.length; i++) {
        // Very rudimentary splitting — aim for about ~800 chars per slide
        if (currentSlideText.length + paragraphs[i].length > 800) {
            let slide = pres.addSlide();
            slide.background = { color: "FFFFFF" };
            slide.addText(title, { x: 0.5, y: 0.5, w: "90%", h: 0.8, fontSize: 28, bold: true, color: darkColor, fontFace });
            slide.addShape(pres.ShapeType.rect, { x: 0.5, y: 1.4, w: 0.3, h: 0.05, fill: { color: themeColor } });
            
            slide.addText(currentSlideText.trim(), { 
                x: 0.5, y: 1.6, w: "90%", h: "75%", 
                fontSize: 16, 
                color: "333333",
                align: "left", 
                valign: "top",
                fontFace
            });
            currentSlideText = paragraphs[i] + "\n\n";
        } else {
            currentSlideText += paragraphs[i] + "\n\n";
        }
    }
    
    if (currentSlideText.trim()) {
        let slide = pres.addSlide();
        slide.background = { color: "FFFFFF" };
        slide.addText(title, { x: 0.5, y: 0.5, w: "90%", h: 0.8, fontSize: 28, bold: true, color: darkColor, fontFace });
        slide.addShape(pres.ShapeType.rect, { x: 0.5, y: 1.4, w: 0.3, h: 0.05, fill: { color: themeColor } });
        
        slide.addText(currentSlideText.trim(), { 
            x: 0.5, y: 1.6, w: "90%", h: "75%", 
            fontSize: 16, 
            color: "333333",
            align: "left", 
            valign: "top",
            fontFace
        });
    }
  };

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line.startsWith('## ') || line.startsWith('### ')) {
      addContentSlide(currentTitle, currentContent);
      currentTitle = line.replace(/^#+\s*/, '').trim();
      currentContent = "";
    } else if (line.trim() !== '' || currentContent !== '') {
      currentContent += line + "\n";
    }
  }
  addContentSlide(currentTitle, currentContent);

  const fileName = `${datasetName.replace(/\.[^/.]+$/, "")}_报告.pptx`;
  pres.writeFile({ fileName });
}

export async function shareReport(reportContent: { summary?: string, insights?: string, charts: any[], markdown: string }) {
  const reportId = uuidv4();
  
  const response = await fetch('/api/report/save', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ reportId, content: reportContent })
  });
  
  if (!response.ok) {
    throw new Error("分享失败，请检查服务状态");
  }
  
  const data = await response.json();
  return data.shareUrl;
}
